fulldata<-read.table("household_power_consumption.txt", sep =";", header = TRUE, dec =".")
filtereddates<-fulldata %>% filter(Date=="1/2/2007" | Date=="2/2/2007")
Sub_metering_1=as.numeric(filtereddates$Sub_metering_1)
Sub_metering_2=as.numeric(filtereddates$Sub_metering_2)
Sub_metering_3=as.numeric(filtereddates$Sub_metering_3)
datetime <- strptime(paste(filtereddates$Date,filtereddates$Time, sep=" "), "%d/%m/%Y %H:%M:%S") 

png(file="plot3.png",width=480, height=480)
plot(datetime,Sub_metering_1,ylab="Energy sub metering",type="l")
lines(datetime, Sub_metering_2, type="l", col="red")
lines(datetime, Sub_metering_3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, lwd=2.5, col=c("black", "red", "blue"))
dev.off()